export const languages = {
    "armenian": {
        "capital": {
            "Ա": { translits: ["a", "A"],   ru: "а" },
            "Բ": { translits: ["b", "B"],   ru: "б" },
            "Գ": { translits: ["g"],        ru: "г" },
            "Դ": { translits: ["d"],        ru: "д" },
            "Ե": { translits: ["e"],        ru: "е (в начале слова — йе)" },
            "Զ": { translits: ["z"],        ru: "з" },
            "Է": { translits: ["ē"],        ru: "э" },
            "Ը": { translits: ["ë"],        ru: "ə (звук между ы и э)" },
            "Թ": { translits: ["th"],       ru: "т с придыханием" },
            "Ժ": { translits: ["zh"],       ru: "ж" },
            "Ի": { translits: ["i"],        ru: "и" },
            "Լ": { translits: ["l"],        ru: "л" },
            "Խ": { translits: ["kh"],       ru: "х" },
            "Ծ": { translits: ["ts"],       ru: "ц (мягкое)" },
            "Կ": { translits: ["k"],        ru: "к" },
            "Հ": { translits: ["h"],        ru: "h (придыхание)" },
            "Ձ": { translits: ["dz"],       ru: "дз" },
            "Ղ": { translits: ["gh"],       ru: "гх (картавое г)" },
            "Ճ": { translits: ["tch"],      ru: "тч" },
            "Մ": { translits: ["m"],        ru: "м" },
            "Յ": { translits: ["y"],        ru: "й" },
            "Ն": { translits: ["n"],        ru: "н" },
            "Շ": { translits: ["sh"],       ru: "ш" },
            "Ո": { translits: ["vo"],       ru: "о (в начале слова — во)" },
            "Չ": { translits: ["ch"],       ru: "ч" },
            "Պ": { translits: ["p"],        ru: "п" },
            "Ջ": { translits: ["j"],        ru: "дж" },
            "Ռ": { translits: ["r"],        ru: "р (раскатистое)" },
            "Ս": { translits: ["s"],        ru: "с" },
            "Վ": { translits: ["v"],        ru: "в" },
            "Տ": { translits: ["t"],        ru: "т" },
            "Ր": { translits: ["r"],        ru: "р (мягкое)" },
            "Ց": { translits: ["ts"],       ru: "ц с придыханием" },
            "Ւ": { translits: ["w"],        ru: "у/в" },
            "Փ": { translits: ["ph"],       ru: "п с придыханием" },
            "Ք": { translits: ["q"],        ru: "к с придыханием" },
            "Օ": { translits: ["ō"],        ru: "о" },
            "Ֆ": { translits: ["f"],        ru: "ф" }
        },
        "lower": {
            "ա": { translits: ["a", "A"],   ru: "а" },
            "բ": { translits: ["b", "B"],   ru: "б" },
            "գ": { translits: ["g", "G"],   ru: "г" },
            "դ": { translits: ["d", "D"],   ru: "д" },
            "ե": { translits: ["e", "E"],   ru: "е (в начале слова — йе)" },
            "զ": { translits: ["z", "Z"],   ru: "з" },
            "է": { translits: ["ē"],        ru: "э" },
            "ը": { translits: ["ë"],        ru: "ə (звук между ы и э)" },
            "թ": { translits: ["th"],       ru: "т с придыханием" },
            "ժ": { translits: ["zh"],       ru: "ж" },
            "ի": { translits: ["i"],        ru: "и" },
            "լ": { translits: ["l"],        ru: "л" },
            "խ": { translits: ["kh"],       ru: "х" },
            "ծ": { translits: ["ts"],       ru: "ц (мягкое)" },
            "կ": { translits: ["k"],        ru: "к" },
            "հ": { translits: ["h"],        ru: "h (придыхание)" },
            "ձ": { translits: ["dz"],       ru: "дз" },
            "ղ": { translits: ["gh"],       ru: "гх (картавое г)" },
            "ճ": { translits: ["tch"],      ru: "тч" },
            "մ": { translits: ["m"],        ru: "м" },
            "յ": { translits: ["y"],        ru: "й" },
            "ն": { translits: ["n"],        ru: "н" },
            "շ": { translits: ["sh"],       ru: "ш" },
            "ո": { translits: ["vo"],       ru: "о (в начале слова — во)" },
            "չ": { translits: ["ch"],       ru: "ч" },
            "պ": { translits: ["p"],        ru: "п" },
            "ջ": { translits: ["j"],        ru: "дж" },
            "ռ": { translits: ["r"],        ru: "р (раскатистое)" },
            "ս": { translits: ["s"],        ru: "с" },
            "վ": { translits: ["v"],        ru: "в" },
            "տ": { translits: ["t"],        ru: "т" },
            "ր": { translits: ["r"],        ru: "р (мягкое)" },
            "ց": { translits: ["ts"],       ru: "ц с придыханием" },
            "ւ": { translits: ["w"],        ru: "у/в" },
            "փ": { translits: ["ph"],       ru: "п с придыханием" },
            "ք": { translits: ["q"],        ru: "к с придыханием" },
            "օ": { translits: ["ō"],        ru: "о" },
            "ֆ": { translits: ["f"],        ru: "ф" }
        }
    }
};
