export const languages = {
    "armenian": {
        "capital": {
            "Ա": { translits: ["а"],                  ru: "а" },
            "Բ": { translits: ["б"],                  ru: "б" },
            "Գ": { translits: ["г"],                  ru: "г" },
            "Դ": { translits: ["д"],                  ru: "д" },
            "Ե": { translits: ["е", "йе"],            ru: "е (в начале слова — йе)" },
            "Զ": { translits: ["з"],                  ru: "з" },
            "Է": { translits: ["э"],                  ru: "э" },
            "Ը": { translits: ["ы", "э", "ə", "ё"],   ru: "ə (звук между ы и э)" },
            "Թ": { translits: ["т"],                  ru: "т с придыханием" },
            "Ժ": { translits: ["ж"],                  ru: "ж" },
            "Ի": { translits: ["и"],                  ru: "и" },
            "Լ": { translits: ["л"],                  ru: "л" },
            "Խ": { translits: ["х"],                  ru: "х" },
            "Ծ": { translits: ["ц"],                  ru: "ц (мягкое)" },
            "Կ": { translits: ["к"],                  ru: "к" },
            "Հ": { translits: ["h", "х"],             ru: "h — глухое придыхание (как англ. house)" },
            "Ձ": { translits: ["дз"],                 ru: "дз" },
            "Ղ": { translits: ["гх", "г"],            ru: "гх (картавое г)" },
            "Ճ": { translits: ["тч"],                 ru: "тч" },
            "Մ": { translits: ["м"],                  ru: "м" },
            "Յ": { translits: ["й"],                  ru: "й" },
            "Ն": { translits: ["н"],                  ru: "н" },
            "Շ": { translits: ["ш"],                  ru: "ш" },
            "Ո": { translits: ["о", "во"],            ru: "о (в начале слова — во)" },
            "Չ": { translits: ["ч"],                  ru: "ч" },
            "Պ": { translits: ["п"],                  ru: "п" },
            "Ջ": { translits: ["дж"],                 ru: "дж" },
            "Ռ": { translits: ["р"],                  ru: "р (раскатистое)" },
            "Ս": { translits: ["с"],                  ru: "с" },
            "Վ": { translits: ["в"],                  ru: "в" },
            "Տ": { translits: ["т"],                  ru: "т" },
            "Ր": { translits: ["р"],                  ru: "р (мягкое)" },
            "Ց": { translits: ["ц"],                  ru: "ц с придыханием" },
            "Ւ": { translits: ["у", "в"],             ru: "у/в" },
            "Փ": { translits: ["п"],                  ru: "п с придыханием" },
            "Ք": { translits: ["к"],                  ru: "к с придыханием" },
            "Օ": { translits: ["о"],                  ru: "о" },
            "Ֆ": { translits: ["ф"],                  ru: "ф" }
        },
        "lower": {
            "ա": { translits: ["а"],                  ru: "а" },
            "բ": { translits: ["б"],                  ru: "б" },
            "գ": { translits: ["г"],                  ru: "г" },
            "դ": { translits: ["д"],                  ru: "д" },
            "ե": { translits: ["е", "йе"],            ru: "е (в начале слова — йе)" },
            "զ": { translits: ["з"],                  ru: "з" },
            "է": { translits: ["э"],                  ru: "э" },
            "ը": { translits: ["ы", "э", "ə", "ё"],   ru: "ə (звук между ы и э)" },
            "թ": { translits: ["т"],                  ru: "т с придыханием" },
            "ժ": { translits: ["ж"],                  ru: "ж" },
            "ի": { translits: ["и"],                  ru: "и" },
            "լ": { translits: ["л"],                  ru: "л" },
            "խ": { translits: ["х"],                  ru: "х" },
            "ծ": { translits: ["ц"],                  ru: "ц (мягкое)" },
            "կ": { translits: ["к"],                  ru: "к" },
            "հ": { translits: ["h", "х"],             ru: "h — глухое придыхание (как англ. house)" },
            "ձ": { translits: ["дз"],                 ru: "дз" },
            "ղ": { translits: ["гх", "г"],            ru: "гх (картавое г)" },
            "ճ": { translits: ["тч"],                 ru: "тч" },
            "մ": { translits: ["м"],                  ru: "м" },
            "յ": { translits: ["й"],                  ru: "й" },
            "ն": { translits: ["н"],                  ru: "н" },
            "շ": { translits: ["ш"],                  ru: "ш" },
            "ո": { translits: ["о", "во"],            ru: "о (в начале слова — во)" },
            "չ": { translits: ["ч"],                  ru: "ч" },
            "պ": { translits: ["п"],                  ru: "п" },
            "ջ": { translits: ["дж"],                 ru: "дж" },
            "ռ": { translits: ["р"],                  ru: "р (раскатистое)" },
            "ս": { translits: ["с"],                  ru: "с" },
            "վ": { translits: ["в"],                  ru: "в" },
            "տ": { translits: ["т"],                  ru: "т" },
            "ր": { translits: ["р"],                  ru: "р (мягкое)" },
            "ց": { translits: ["ц"],                  ru: "ц с придыханием" },
            "ւ": { translits: ["у", "в"],             ru: "у/в" },
            "փ": { translits: ["п"],                  ru: "п с придыханием" },
            "ք": { translits: ["к"],                  ru: "к с придыханием" },
            "օ": { translits: ["о"],                  ru: "о" },
            "ֆ": { translits: ["ф"],                  ru: "ф" }
        }
    }
};
